spring.application.name=demo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}        # <- Secret
spring.datasource.username=${DB_USER}  # <- Secret
spring.datasource.password=${DB_PASS}  # <- Secret

# En CI normalmente NO quieres que te migre/escriba la BD:
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JWT desde Secret (Base64 de 256 bits, por ejemplo)
security.jwt.secret-base64=${JWT_SECRET_BASE64}
security.jwt.expiration-ms=3600000

management.server.port=8081
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Log más silencioso en CI (ajusta si quieres)
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO
logging.level.org.hibernate.orm.jdbc.extract=INFO
spring.jpa.properties.hibernate.generate_statistics=false

logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.web=INFO
